# Generated by Django 3.1.5 on 2021-02-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='summary',
            field=models.CharField(default='this is a tutorial', max_length=200),
        ),
    ]
